# elastic-stack/filebeat/filebeat.yml
# logging.level: debug
# logging.to_files: true
# logging.files:
#   path: /var/log/filebeat
#   name: filebeat.log
#   keepfiles: 7
#   permissions: 0644

filebeat.inputs:
  - type: container
    paths:
      - /var/lib/docker/containers/*/*.log
    processors:
      - add_docker_metadata: ~
      - drop_event:
          when:
            not:
              equals:
                docker.container.labels.logging: "enabled"

output.elasticsearch:
  hosts: ["${ELASTICSEARCH_URL}"]
  api_key: ${ELASTICSEARCH_FILEBEAT_APIKEY}
  ssl.verification_mode: full
  # ssl.certificate_authorities: ["/etc/filebeat/certs/rootCA.crt"]
  # ssl.certificate: "/etc/filebeat/certs/filebeat.crt"
  # ssl.key: "/etc/filebeat/certs/filebeat.key"


