variable "DB_USER" {}
variable "DB_PASS" {}
variable "DB_NAME" {}
variable "OTEL_COLLECTOR_URL" {}
variable "OTEL_TOKEN" {}
variable "ELASTIC_APM_URL" {}
variable "ELASTIC_APM_TOKEN" {}
variable "NEWRELIC_API_KEY" {}
variable "OTEL_LGTM_URL" {}
variable "NEWRELIC_URL" {}
variable "STACK_VERSION" {}
variable "ELASTIC_PASSWORD" {}
variable "CLUSTER_NAME" {}
variable "KIBANA_PASSWORD" {}
variable "LICENSE" {}
variable "ENCRYPTION_KEY" {}
variable "ES_PORT" {}
variable "KIBANA_PORT" {}
variable "FLEET_PORT" {}
variable "APMSERVER_PORT" {}
variable "ES_MEM_LIMIT" {}
variable "KB_MEM_LIMIT" {}
variable "LS_MEM_LIMIT" {}
variable "ELASTICSEARCH_URL" {}
variable "ELASTICSEARCH_FILEBEAT_APIKEY" {}
variable "ELASTIC_APM_SECRET_TOKEN" {}
